name: Lerna Publish Stable 1.x

on:
  pull_request:
    branches: [stable_1.x]
    types: [closed]
  push:
    branches:
      - stable_1.x
jobs:
  publish_release:
    name: Publish release
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.main.ref }}
      - run: git fetch --prune --unshallow

      - uses: actions/setup-node@v1
        with:
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          node-version: '12.x'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure CI Git User
        run: |
          git config --global user.email octobot@github.com
          git config --global user.name GitHub Actions

      - run: yarn install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - name: 'Build all'
        run: yarn build
      - name: 'Publish stable 1.x to NPM'
        run: yarn lerna publish --conventional-graduate --yes --dist-tag 1 --force-publish --exact
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
